# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doug Cooper
email: douglas.cooper1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple website for jotting down progress with various home electronics and software projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dougcooper.github.io" # the base hostname & protocol for your site
twitter_username: "@dCo0p"
github_username:  dougcooper
linkedin_username: douglascooper1

# Build settings
markdown: kramdown

theme: jekyll-theme-architect

gems:
  - jekyll-seo-tag
